// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMw6yz5mzhMb7Japc2AeELmXpHQNwTke4',
    appId: '1:346661661119:web:350b0fdb25a9550f6e590a',
    messagingSenderId: '346661661119',
    projectId: 'tasking-3f408',
    authDomain: 'tasking-3f408.firebaseapp.com',
    storageBucket: 'tasking-3f408.firebasestorage.app',
    measurementId: 'G-EWJCBC3DNV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSlg8AW2n1fYIkoAIu27DagffjJNgC0fU',
    appId: '1:346661661119:android:25ffaacbf5474a716e590a',
    messagingSenderId: '346661661119',
    projectId: 'tasking-3f408',
    storageBucket: 'tasking-3f408.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0dzynOFjM_ClFfEXqaT9kojp-ciXX7h8',
    appId: '1:346661661119:ios:aa2e1ba9b4351ff36e590a',
    messagingSenderId: '346661661119',
    projectId: 'tasking-3f408',
    storageBucket: 'tasking-3f408.firebasestorage.app',
    iosBundleId: 'com.example.tasking',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0dzynOFjM_ClFfEXqaT9kojp-ciXX7h8',
    appId: '1:346661661119:ios:aa2e1ba9b4351ff36e590a',
    messagingSenderId: '346661661119',
    projectId: 'tasking-3f408',
    storageBucket: 'tasking-3f408.firebasestorage.app',
    iosBundleId: 'com.example.tasking',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAMw6yz5mzhMb7Japc2AeELmXpHQNwTke4',
    appId: '1:346661661119:web:1193e36336be7df86e590a',
    messagingSenderId: '346661661119',
    projectId: 'tasking-3f408',
    authDomain: 'tasking-3f408.firebaseapp.com',
    storageBucket: 'tasking-3f408.firebasestorage.app',
    measurementId: 'G-0N8GB0FTEP',
  );
}
